version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gocritic

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
