run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - revive
    - gocritic

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
