events {}

http {

    upstream payment_backend {
        server payment-service-v1:8080;
        # server payment-service-v2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://payment_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
